### ISSUE TITLE
SNOW-1408580: ERROR "No active warehouse selected in the current session" for snow streamlit deploy

### ISSUE THREAD

**Issue by RobindeGrootNL** [snowflakedb/snowflake-cli#1062]
### SnowCLI version

2.2.0

### Python version

3.11.8

### Platform

macOS-14.4.1-arm64-arm-64bit

### What happened

I am deploying a streamlit app through the snow cli, using the following command:

```
snow streamlit deploy \
  --temporary-connection \
  --replace \
  --account $(SNOWFLAKE_ACCOUNT_FULL) \
  --schema $(SNOWFLAKE_SCHEMA_STREAMLIT) \
  --role $(SNOWFLAKE_ROLE_STREAMLIT) \
  --debug
```

The other SNOWFLAKE environment variables are defined further above and are available to the snowCLI (evidenced by the deploy going as planned). The weird thing is that I get the following console output with an error "No active warehouse selected in the current session", even though I set the SNOWFLAKE_WAREHOUSE env variable, and it happens even when appending --warehouse $(SNOWFLAKE_WAREHOUSE) to the above command. The link that is given back by the snowCLI does work (but truncated here for security reasons) and the streamlit app functions as it should.

It seems to me like the streamlit app will use the SNOWFLAKE_WAREHOUSE I set for querying databases and running the dashboard code, but that somehow the warehouse for running the CREATE STREAMLIT etc. commands is not defined. I would expect this to be 'settable', or for the error print to go away if it still manages to complete the operation successfully.

### Console output

```Shell
-- [DO  ] Deploying streamlit app example_streamlit...
2024-05-13 16:28:56 ERROR Cannot determine regionless redirect; assuming True.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/snowcli/2.2.0/libexec/lib/python3.12/site-packages/snowflake/cli/plugins/connection/util.py", line 36, in is_regionless_redirect
    *_, cursor = conn.execute_string(REGIONLESS_QUERY, cursor_class=DictCursor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/snowcli/2.2.0/libexec/lib/python3.12/site-packages/snowflake/connector/connection.py", line 857, in execute_string
    ret = list(stream_generator)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/snowcli/2.2.0/libexec/lib/python3.12/site-packages/snowflake/connector/connection.py", line 875, in execute_stream
    cur.execute(sql, _is_put_get=is_put_or_get, **kwargs)
  File "/opt/homebrew/Cellar/snowcli/2.2.0/libexec/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/opt/homebrew/Cellar/snowcli/2.2.0/libexec/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/snowcli/2.2.0/libexec/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/opt/homebrew/Cellar/snowcli/2.2.0/libexec/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000606 (57P03): 01b44d64-0103-b50e-0003-8902eda35d47: No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

Streamlit successfully deployed and available under https://app.snowflake.com/..........
```

### How to reproduce

1. Create a streamlit app using `snow streamlit init`.
2. Add all necessary snowflake env variables to the environment you're working in so they are accessible in the terminal.
3. Run `snow streamlit deploy --temporary-connection --replace` and specify more env variables if needed for the deploy.
4. Read the output and see that there was an error but that the deploy still went the way it should.

**Comment by sfc-gh-turbaszek** [comment]
I'm able to replicate the behavior. 

1. Uploading files does not require warehouse
2. Creating Streamlit (ddl operation) does not require warehouse
3. Determining url requires running a query which requires a warehouse.

This cause the above error. In fact we do handle the exception but for some weird reason we are logging it.
