### ISSUE TITLE
PYI-31084:ERROR since upgrading to version 3.2.1 - Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!

### ISSUE THREAD

**Issue by markSmurphy** [snowflakedb/snowflake-cli#1930]
### SnowCLI version

3.2.1

### Python version

Python 3.12.7

### Platform

Windows-10-10.0.19045-SP0

### What happened

I upgrade from version 3.2.0 to **3.2.1** via the MSI installer, and ran a `snow app run` command and got the error:

> [PYI-29220:ERROR] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!

I then tried `snow --version` and received the same error.

```shell
PS C:\Users\> snow --version
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 54, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 16, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'
[PYI-31084:ERROR] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

I uninstalled 3.2.1 and reinstalled 3.2.0 and things are back to working as expected

### Console output

```Shell
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 54, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 16, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'
[PYI-31084:ERROR] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

### How to reproduce

I can reproduce it with every `snow` command I've triedwith version 3.2.1 installed.

1. Had 3.2.0 installed
2. Downloaded 3.2.1 msi installer
3. Execute .msi file and let it upgrade the installation
4. Run `snow --version` from the console

**Comment by sfc-gh-mraba** [comment]
Hi,

Please uninstall Snowflake-CLI 3.2.0 from Installed apps in Windows Settings and install newer version >=3.2.1.
This should solve the problem with upgrades in the future.

**Comment by markSmurphy** [comment]
I can confirm that simply upgrading to v3.2.2 did fail, while uninstalling via the `msi` and installing v3.2.2 has worked.
Although I would expect an upgrade to work, so I think this is a workaround rather than a resolution.
Thanks

**Comment by sfc-gh-mraba** [comment]
We checked upgrade paths.
The issue is related for upgrading from <= 3.2.0
Upgrades from >= 3.2.1 works as expected.
